#!/bin/bash

fnc_iniciar(){
    echo "iniciar"
    ##Falta estado bridge por iniciar si ya esta funcionando
    ## Crear bridge parte interna
    ip l a name br0 type bridge vlan_filtering 1
    ip l s dev br0 up

    for LINIA in $(cat "/usr/local/JSBach/conf/bridge.conf" | grep -v '^#'); do
        VLANID=$(echo "$LINIA"|cut -d';'  -f2)
        VLANIP=$(echo "$LINIA"|cut -d';'  -f4)
        ip l a l br0 name br0.$VLANID type vlan id $VLANID
        ip l s dev br0.$VLANID up
        ip a a dev br0.$VLANID $VLANIP
    done

    for LINIA in $(cat "/usr/local/JSBach/conf/bridge_if.conf" | grep -v '^#'); do
        NOMBRE_IF=$(echo "$LINIA" | cut -d ';' -f1)
        VLAN_UNTAG=$(echo "$LINIA" | cut -d ';' -f2)
        VLAN_TAG=$(echo "$LINIA" | cut -d ';' -f3)
        ip l s dev $NOMBRE_IF master br0
        if [ ! -z $VLAN_UNTAG ]; then
            bridge vlan add dev $VLAN_IF vid $VLAN_UNTAG pvid untagged
        fi

        if [ ! -z $VLAN_TAG ]; then
            for CAMP in ${VLAN_TAG//,/ }; do 
                bridge vlan add dev $VLAN_IF vid $VLAN_TAG
            done
        fi
    done    
}

fnc_parar(){
    echo "parar"
    ip l d dev br0
}

fnc_configurar(){
    echo "config"
}
fnc_estado(){
    echo "estado"
}

######################################################################
###  MAIN
######################################################################

MSG="falta [iniciar, aturar, configurar ,estat]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
  echo "$MSG"
  exit 1
fi

OPCIO_1=$1
shift

# Fem switch per executar la funció que toca
case "$OPCIO_1" in
  iniciar)
    fnc_iniciar  $@
    ;;
  parar)
    fnc_parar	$@
    ;; 
  configurar) 
    fnc_configurar $@
    ;;
  estat) 
    fnc_estat $@
    ;;
  *)
    echo "$MSG"
    ;;
esac

