#!/bin/bash

######################################################################
###  Funcions
######################################################################

# Comprobar root
if [ "$(id -u)" -ne 0 ]; then
	echo "Aquest script s'ha d'executar com a root"
	exit 1
fi

fnc_iniciar(){
	fnc_aturar
	echo "Iniciar"

	# Crear cadenes per VLAN
	while IFS= read -r linia; do
	    [ -z "$linia" ] && continue

	    nom=$(echo "$linia" | cut -d';' -f1)
	    ip=$(echo "$linia"  | cut -d';' -f3)

	    # Crear cadena només si no existeix
	    iptables -L "$nom" -n >/dev/null 2>&1 || iptables -N "$nom"
	    iptables -A FORWARD -s "$ip" -j "$nom"
	done < <(grep -v '^#' /usr/local/JSBach/conf/bridge.conf)

	# Cadena ports_wls
	iptables -L ports_wls -n >/dev/null 2>&1 || iptables -N ports_wls

	while IFS= read -r linia; do
	    [ -z "$linia" ] && continue

	    protocol=$(echo "$linia" | cut -d';' -f1)
	    num_port=$(echo "$linia" | cut -d';' -f2)

	    iptables -A ports_wls -p "$protocol" --dport "$num_port" -j ACCEPT
	done < <(grep -v '^#' /usr/local/JSBach/conf/ports_wls.conf)

	iptables -A ports_wls -j DROP
}

fnc_aturar(){
	echo "Parando"

	iptables -F
	iptables -X
	iptables -P FORWARD ACCEPT
	iptables -P INPUT ACCEPT
	iptables -P OUTPUT ACCEPT

	resultat=$(/usr/local/JSBach/scripts/enrutar estado)

	if echo "$resultat" | grep -q "ACTIVAT"; then
		iptables -t nat -F
		iptables -t nat -X
		/usr/local/JSBach/scripts/enrutar iniciar
	else
		iptables -t nat -F
		iptables -t nat -X
	fi
}

fnc_configurar(){
	echo "Configuracion"

	# Si no se pasa ninguna acción
	if [ $# -lt 1 ]; then
		echo "Falta [ conectar | desconectar | conectar_puertos_wls ]:"
		exit 1
	fi

	ARG_1=$1
	shift

	# Si no se pasa vlan
	if [ $# -lt 1 ]; then
		echo "Falta vlan"
		exit 1
	fi

	case "$ARG_1" in
	  desconectar)
	        linia=$(grep ";$1;" /usr/local/JSBach/conf/bridge.conf)
	        nom=$(echo "$linia" | cut -d';' -f1)
	        vid=$(echo "$linia" | cut -d';' -f2)

	        if [ -z "$nom" ]; then
		    	echo "Error no existe la vlan $1"
			else
			    iptables -F "$nom"

			    # IPs privilegiadas
			 	while IFS= read -r ipwls; do
				    ip=$(echo "$ipwls" | cut -d';' -f2)
					mac=$(echo "$ipwls" | cut -d';' -f3)
				    iptables -A "$nom" -s "$ip" -m mac --mac-source "$mac" -j ACCEPT
				done < <(grep -v '^#' /usr/local/JSBach/conf/ip_wls.conf | grep "^$vid;")

			    iptables -A "$nom" -j DROP
			fi
	  	;;
	  conectar)
	        linia=$(grep ";$1;" /usr/local/JSBach/conf/bridge.conf)
	        nom=$(echo "$linia" | cut -d';' -f1)

	        if [ -z "$nom" ]; then
		    	echo "ERROR, no existe la vlan $1"
			else
				iptables -F "$nom"
			fi
	  	;;
	  conectar_puertos_wls)
	        linia=$(grep ";$1;" /usr/local/JSBach/conf/bridge.conf)
	        nom=$(echo "$linia" | cut -d';' -f1)
	        vid=$(echo "$linia" | cut -d';' -f2)

	        if [ -z "$nom" ]; then
		    	echo "ERROR, no existe la vlan $1"
			else
				iptables -F "$nom"

			 	while IFS= read -r ipwls; do
				    ip=$(echo "$ipwls" | cut -d';' -f2)
				    mac=$(echo "$ipwls" | cut -d';' -f3)
				    iptables -A "$nom" -s "$ip" -m mac --mac-source "$mac" -j ACCEPT
				done < <(grep -v '^#' /usr/local/JSBach/conf/ip_wls.conf | grep "^$vid;")

				iptables -A "$nom" -j puertos_wls
			fi
	  	;;
	  *)
	        echo "Error argumentos:"
	        echo "  conectar <vlan>"
	        echo "  desconectar <vlan>"
	        echo "  conectar_puertos_wls <vlan>"
	        ;;
	esac
}


fnc_estat(){
	echo "Puedes poner el nombre de la vlan"
	if [ $# -eq 0 ]; then
		 echo MAIN
		 iptables -nvL --line-numbers
		 echo
		 echo NAT
		 iptables -t nat -nvL --line-numbers
		 echo "Puedes poner el nombre de la vlan"
		 exit 0
	fi


	linia=$(grep ";$1;" /usr/local/JSBach/conf/bridge.conf)
	nom=$(echo "$linia" | cut -d';' -f1)

	if [ -z "$nom" ]; then
		echo "ERROR, No existe la vlan $1"
	else
		if iptables -C "$nom" -j DROP 2>/dev/null; then
			echo "DESCONNECTADA"
		else
			echo "CONNECTADA"
		fi
	fi
}

######################################################################
###  MAIN
######################################################################

MSG="falta [iniciar, parar, configurar o estado]"

if [ $# -lt 1 ]; then
  echo "$MSG"
  exit 1
fi

OPCIO_1=$1
shift

case "$OPCIO_1" in
  iniciar)
    fnc_iniciar "$@"
    ;;
  parar)
    fnc_aturar "$@"
    ;;
  configurar)
    fnc_configurar "$@"
    ;;
  estado)
    fnc_estat "$@"
    ;;
  *)
    echo "$MSG"
    ;;
esac
