#!/bin/bash

source /usr/local/JSBach/conf/enrutar.conf

######################################################################
###  Funcions
######################################################################

fnc_autor(){
 echo "                       _"
 echo "                     ('v')"
 echo "                    //-=-\\ "
 echo "                    (== ==)"
 echo "                     ^^ ^^"
 echo "###############################################"
 echo "########## ALESSANDRO ZANTI ALCALÁ ############"
 echo "###############################################"
}


fnc_iniciar(){
	echo "Iniciar"	
	echo 1 > /proc/sys/net/ipv4/ip_forward
	iptables -t nat -A POSTROUTING -o $ENR_DEV -j MASQUERADE
	
}

fnc_configurar(){
  (
    echo ENR_DEV=$1
  ) > /usr/local/JSBach/conf/enrutar.conf

if [ $# -lt 1 ]; then
  echo "Falta [Device]"
  exit 1
fi

}

fnc_parar(){
	echo "Parar"
	echo 0 > /proc/sys/net/ipv4/ip_forward
	iptables -t nat -D POSTROUTING -o $ENR_DEV -j MASQUERADE
}


fnc_estado()
{

	if [ "$(cat /proc/sys/net/ipv4/ip_forward)" -eq 1 ] && iptables -t nat -C POSTROUTING -o "$ENR_DEV" -j MASQUERADE 2>/dev/null; then
	    echo "ACTIVADO"
	else
	    echo "DESACTIVADO"	
	fi
}


######################################################################
###  MAIN
######################################################################

MSG="Falta: [Iniciar, Parar, Configurar o Estado]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
  echo "$MSG"
  exit 1
fi


OPCIO_1=$1
shift

# Fem switch per executar la funció que toca
case "$OPCIO_1" in
  iniciar)
    fnc_autor  $@
    fnc_iniciar  $@
    ;;
  configurar)
    fnc_autor $@
    fnc_configurar $@
    ;;
  parar)
    fnc_autor  $@
    fnc_parar	$@
    ;; 
  estado) 
    fnc_autor  $@
    fnc_estado $@
    ;;
  *)
    echo "$MSG"
    ;;
esac


