#!/bin/bash

source /usr/local/JSBach/conf/ifwan.conf

##########################################################################
###  FUNCTIONS
##########################################################################
fnc_autor(){
 echo "                       _"
 echo "                     ('v')"
 echo "                    //-=-\\ "
 echo "                    (== ==)"
 echo "                     ^^ ^^"
 echo "###############################################"
 echo "########## ALESSANDRO ZANTI ALCALÁ ############"
 echo "###############################################"
}


fnc_parar(){
    echo $IFW_MODE
    case "$IFW_MODE" in
    "dhcp")
        dhcpcd -k $IFW_DEV
         sudo systemctl stop NetworkManager 2>/dev/null
         sudo systemctl disable NetworkManager 2>/dev/null
         #echo "NetworkManager detenido y deshabilitado."
         sudo systemctl status NetworkManager
         echo DHCP parado
         ;;
    "manual")
        echo MANUEL parado
        ip a d $IFW_IP/$IFW_MASC dev $IFW_DEV
        ip l s dev $IFW_DEV down
        ;;
    esac
}

fnc_configurar(){
    (
    echo IFW_MODE=$1
    echo IFW_DEV=$2
    echo IFW_IP=$( echo $3 | cut -d'/' -f1)
    echo IFW_MASC=$( echo $3 | cut -d'/' -f2)
    echo IFW_PE=$4
    echo IFW_S_DNS=$5
    ) > /usr/local/JSBach/conf/ifwan.conf

     if [ $# -lt 1 ]; then 
        echo "Falta modo: [dhcp/manual]"
        exit 1
    fi

    shift

    if [ $# -lt 1 ]; then
        echo "[Falta interfaz]"
        exit 1
    fi
}

fnc_iniciar() {
    if [ "$IFW_MODE" == "dhcp" ]; then
        dhcpcd "$IFW_DEV"
        return 0
    fi
 
    if [ "$IFW_MODE" == "manual" ]; then
        ip a a $IFW_IP/$IFW_MASC dev $IFW_DEV
        ip l s dev $IFW_DEV up  
        ip r a defualt via $IFW_PE
        if grep "#DNS=" /etc/systemd/resolved.conf; then 
             sed -i 's/#DNS=*/DNS='$IFW_S_DNS'/g' /etc/systemd/resolved.conf
        fi

        if ! grep "DNS=$IFW_S_DNS" /etc/systemd/resolved.conf; then   
            sed -i 's/^DNS=.*/DNS='$IFW_S_DNS'/g' /etc/systemd/resolved.conf
        fi
    return 0
    exit 1
    fi

    if [ $# -lt 1 ]; then
        echo "falta el modo : manual o dhcpcd"
        exit 1
    fi
    return 0
    echo "Modo no soportado: echo $IFW_MODE"
    exit 1
}

fnc_estado(){
    if wget -q --spider http://google.com; then
        echo "Conectado a INTERNET"
    else
        echo "NO conectado a INTERNET"
    fi
}
fnc_modificar_fichero(){
    fichero=$1
    linea=$2
    nuevo=$3
}

##########################################################################
###  MAIN
##########################################################################

MSG="[Parar/Iniciar/Configurar]"

if [ $# -lt 1 ]; then
    echo "$MSG"
    exit 1
fi

option_1=$1
shift

case "$option_1" in
    parar)
        fnc_autor "$@"
        fnc_parar "$@"
    ;;
    configurar)
        fnc_autor "$@"
        fnc_configurar "$@"
    ;;
    iniciar)
        fnc_autor "$@"
        fnc_iniciar "$@"
        fnc_estado "$@"
    ;;
    estado)
        fnc_autor "$@"
        fnc_estado "$@"
    ;;
    autor)
        fnc_autor "$@"
    ;;
    *)
        echo "$MSG"
    ;;
esac

#   _
# ('v')
#//-=-\
#(== ==)
# ^^ ^^
 ###############################################
 ########### ALESSANDRO ZANTI ALCALA ############
 ###############################################
