#!/bin/bash

source /usr/local/JSBach/conf/interfaces.conf

##########################################################################
###  FUNCTIONS
##########################################################################

fnc_autor(){
 echo "                       _"
 echo "                     ('v')"
 echo "                    //-=-\\ "
 echo "                    (== ==)"
 echo "                     ^^ ^^"
 echo "###############################################"
 echo "########## ALESSANDRO ZANTI ALCALÁ ############"
 echo "###############################################"
}

fnc_listar_tarjetas(){
    echo "Obteniendo interfaces de red..."
    FECHA=$(date '+%Y-%m-%d %H:%M:%S')
    SALIDA="/usr/local/JSBach/conf/interfaces.conf"

    # Creamos carpeta si no existe
    mkdir -p /usr/local/JSBach/logs

    echo "Listado de interfaces de red - $FECHA" > "$SALIDA"
    echo "--------------------------------------" >> "$SALIDA"

    # Obtenemos los nombres de las interfaces
    mapfile -t IFACES < <(ip -o link show | awk -F': ' '{print $2}')

    CONTADOR=1
    for IFACE in "${IFACES[@]}"; do
        printf "%2d - %s\n" "$CONTADOR" "$IFACE" >> "$SALIDA"
        ((CONTADOR++))
    done

    echo " "
    echo "Interfaces encontradas:"
    cat "$SALIDA"
    echo " "
    echo "Archivo guardado en: $SALIDA"
}

##########################################################################
###  MAIN
##########################################################################

MSG="[listar/autor]"

if [ $# -lt 1 ]; then
    echo "$MSG"
    exit 1
fi

OPCION=$1
shift

case "$OPCION" in
    listar)
        fnc_autor "$@"
        fnc_listar_tarjetas "$@"
    ;;
    autor)
        fnc_autor "$@"
    ;;
    *)
        echo "$MSG"
    ;;
esac
